Add generic helper functions (#3264)
* Changed MethodInfo to allow generic types.

* Modified error handling in Typer and DefinitionExtractor

* Moved ExpressionParseError into a new file

* Changed error handling and made definition extractor ignore advanced function classes

* Added annotation for helper functions

* Added support for generic functions declared in files

* Added missing files

* Minor changes

* Example of specifying types for FE

* Added setup for serialization of MethodInfo

* Renaming variables and text fixes

* Some updates to tests

* Some changes to exceptions and tests

* Changed more errors to use new hierarchy

* Removed OtherError

* Fixed duplicate methods.

* Simplified error in ClassExtractionBaseTest

* Fixes to serialization and ClassExtractionBaseTest

* Moved example generic function from geo to DevProcessConfigCreator

* Added other example function

* Fixed names of parameters in test

* Moved TypeInfos to separate class

* Renamed variable

* Added another example generic function.

* Fixed implementation of example generic function

* Fixed DevClassExtractionTest

* Added more error messages to MethodInfo.apply

* Stylistic changes to MethodInfo.apply

* Removed use of applyForArray

* Renamed SimpleMethodInfo to NoVarArgMethodInfo and added some type safety to ClassExtractionBaseTest

* Separated out extractGenericMethod

* Cleaned imports in geo

* Fixed compilation errors after rebase

* Created test for extraction of generic functions.

* Removed zip function from tests.

* Changed TypingFunction interface

* Corrected head function used for tests

* Added part of test for handling incorrect

* Changed one test in EspTypeUtilsSpec

* Corrected behaviour for java classes.

* Corrected wrong method names when accessors are generated

* Corrected bug in generating method names

* Added tests for EspTypeUtils

* Renamed TypedInfos to TypedInfo

* Added tests for creating MethodInfos

* Added serialization test

* Renamed NoVarArgMethodInfo

* Added some tests for generating functions for StaticMethodInfo

* Added more tests for TypeInfo

* Moved some errors closer to spel

* Moved custom error declarations

* Moved error declarations back to scala

* Modified error handling in java

* Removed duplicated test

* Corrected tests in TypeInfoSpec + stylistic changes

* Updated snapshots

* Stylistic changes

* Changed combining validatedNel in TypeMethodReference

* Reworked TypeMethodReference

* Fixed tests after changing ArgumentTypeError

* Added missing import

* Renamed TypeInfo to TypeInfos

* Readded some imports

* Corrected TypeMethodReference

* Renamed some variables

* Renamed MethodInfo.apply

* Docs and name changes in TypingFunction

* Minor fix in EspTypeUtils

* Renamed ExpressionParseError

* Used Ior in one place in TypeMethodReference

* Revert "Used Ior in one place in TypeMethodReference"

This reverts commit 695f71b6ad992a02f75f24204ed7346aa1160f9e.

* Added docs to TypingFunction

* Modified names in tests

* Removed forgotten debug

* Added better error messages for incorrect HelperFunctions

* Added changelog entry

* Removed name from MethodInfo

* Corrected combining errors

* Corrected error message when trying to subtract strings and fixed test for it

* Modified rethrowing exception

* Corrected equality of Signatures

* Removed name from FunctionalMethodInfo

* Added example functions to GenericHelperFunction

* Removed old FIXME

* Checked and removed old TODOs and FIXMEs

Co-authored-by: Dawid Sula <dsl@touk.pl>
Co-authored-by: dawidsula26 <dawidsula26@users.noreply.github.com>